steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/notun-alo-rag"
      - "-f"
      - "Dockerfile.rag"
      - "."
images:
  - "gcr.io/$PROJECT_ID/notun-alo-rag"
