<?php
// lang.php - Localization Dictionary

startSession();

// Set default language to English if not set
if (!isset($_SESSION['lang'])) {
    $_SESSION['lang'] = 'en';
}

// Allow toggling language via GET parameter ?lang=bn or ?lang=en
if (isset($_GET['lang']) && in_array($_GET['lang'], ['en', 'bn'])) {
    $_SESSION['lang'] = $_GET['lang'];
    // Redirect back to same page without lang parameter to avoid keeping it in URL
    $url = strtok($_SERVER["REQUEST_URI"], '?');
    header("Location: " . $url);
    exit();
}

$currentLang = $_SESSION['lang'];

function en2bn($number) {
    global $currentLang;
    if ($currentLang !== 'bn') return $number;
    $eng = ['0','1','2','3','4','5','6','7','8','9'];
    $bng = ['০','১','২','৩','৪','৫','৬','৭','৮','৯'];
    return str_replace($eng, $bng, $number);
}

function translateStatus($status) {
    global $lang;
    $lower = strtolower($status);
    return $lang[$lower] ?? ucfirst($status);
}

$translations = [
    'en' => [
        'edit_profile_sub' => 'Update your personal information',
        'full_name' => 'Full Name',
        'phone_number' => 'Phone Number',
        'address' => 'Address',
        'upload_profile_picture' => 'Upload Profile Picture',
        'site_title' => 'Notun Alo',
        'dashboard' => 'Dashboard',
        'shop' => 'Shop',
        'ai_assistant' => 'AI Assistant',
        'edit_profile' => 'Edit Profile',
        'logout' => 'Logout',
        'hello' => 'Hello',
        'recycling_overview' => 'Here\'s your recycling overview',
        'visit_shop' => 'Visit Shop',
        'leaderboard_progress' => 'Leaderboard Progress',
        'current_rank' => 'Current Rank:',
        'next_rank' => 'Next Rank:',
        'max_rank_reached' => 'Max Rank Reached!',
        'pts' => 'pts',
        'reward_points' => 'Reward Points',
        'points_hint' => 'Points available to spend',
        'completed_pickups' => 'Completed Pickups',
        'sessions_hint' => 'Total recycling sessions',
        'total_recycled' => 'Total Recycled',
        'weight_hint' => 'Waste diverted from landfill',
        'request_pickup' => 'Request a Pickup',
        'schedule_hint' => 'Schedule your next recycling collection',
        'waste_category' => 'Waste Category',
        'select_type' => '— Select type —',
        'paper_option' => '📄 Paper (5 pts/KG)',
        'plastic_option' => '🧴 Plastic (8 pts/KG)',
        'metal_option' => '🔩 Metal (12 pts/KG)',
        'paper' => 'Paper',
        'plastic' => 'Plastic',
        'metal' => 'Metal',
        'estimated_weight' => 'Estimated Weight (KG)',
        'preferred_date' => 'Preferred Pickup Date',
        'submit_request' => 'Submit Request',
        'recent_activity' => 'My Recent Activity',
        'activity_hint' => 'Your pickup history and statuses',
        'no_pickups' => 'No pickups yet. Request your first one!',
        'scheduled' => 'Scheduled:',
        'top_recyclers' => 'Top Recyclers Leaderboard',
        'top_recyclers_hint' => 'The best of Notun Alo',
        'search_products' => 'Search products by name...',
        'recycling' => 'Recycling',
        'trash_to_treasure' => 'Trash to Treasure',
        'schedule_pickup' => 'Schedule Pickup',
        'agency_portal' => 'Agency Portal',
        'assigned_tasks' => 'Assigned Tasks',
        'pending_tasks' => 'Pending Tasks',
        'tasks_requiring_collection' => 'Tasks requiring collection',
        'all_caught_up' => 'All caught up! No pending tasks assigned to you.',
        'recently_completed' => 'Recently Completed',
        'last_10_completed' => 'Last 10 completed pickups',
        'actual_weight_collected' => 'Actual Weight Collected (KG)',
        'mark_as_collected' => 'Mark as Collected',
        'admin_dashboard' => 'Admin Dashboard',
        'platform_stats' => 'Overview of platform statistics',
        'total_waste_collected' => 'Total Waste Collected',
        'total_pickups' => 'Total Pickups',
        'registered_users' => 'Registered Users',
        'products_in_shop' => 'Products in Shop',
        'user' => 'USER',
        'category' => 'CATEGORY',
        'weight' => 'WEIGHT',
        'date' => 'DATE',
        'action' => 'ACTION',
        'my_tasks' => 'My Tasks',
        'pickups' => 'Pickups',
        'orders' => 'Orders',
        'add_product' => 'Add Product',
        'inventory' => 'Inventory',
        'manage_orders' => 'Manage Orders',
        'manage_orders_sub' => 'View product purchases and assign delivery agencies',
        'product' => 'Product',
        'payment' => 'Payment',
        'status' => 'Status',
        'assign_agency' => 'Assign Agency',
        'assign' => 'Assign',
        'select' => '— Select —',
        'no_orders_found' => 'No orders found.',
        'manage_pickups' => 'Manage Pickups',
        'manage_pickups_sub' => 'View user pickup requests and assign to agencies',
        'inventory_management' => 'Inventory Management',
        'inventory_sub' => 'All products currently in the upcycle shop',
        'add_new_product' => 'Add New Product',
        'add_product_sub' => 'Create a new eco-friendly product for the shop',
        'confirmed' => 'Confirmed',
        'pending' => 'Pending',
        'completed' => 'Completed',
        'assigned' => 'Assigned',
        'points' => 'Points',
        'cash' => 'Cash',
        'points_price' => 'Points Price',
        'cash_price' => 'Cash Price',
        'stock' => 'Stock',
        'actions' => 'Actions',
        'left' => 'left',
        'out_of_stock' => 'Out of stock',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'delete_confirm' => 'Are you sure you want to delete this product?',
        'product_name' => 'Product Name',
        'image_url' => 'Image URL',
        'description' => 'Description',
        'price_bdt' => 'Price (BDT)',
        'add_product_btn' => 'Add Product to Shop',
        'edit_product' => 'Edit Product',
        'edit_product_sub' => 'Update product details below',
        'update_product' => 'Update Product',
        'back_to_inventory' => 'Back to Inventory',
        'save_changes' => 'Save Changes',
        'no_users_yet' => 'No recyclers yet.',
        'environmental_impact' => 'Environmental Impact',
        'sustainability_report' => 'Sustainability Report',
        'impact_intelligence' => 'Environmental Impact Intelligence',
        'impact_desc' => 'Your recycling translated into climate, water, and energy savings.',
        'co2_prevented' => 'CO2 prevented',
        'car_trips_avoided' => 'car trips avoided',
        'water_saved' => 'Water saved',
        'bottles_saved' => 'bottles saved',
        'energy_saved' => 'Energy saved',
        'phone_charges' => 'phone charges',
        'live_impact_loaded' => 'Live impact loaded',
        'forecast_90_days' => '90-day forecast',
        'loading_forecast' => 'Loading forecast...',
        'story_default' => 'Every completed pickup will appear here as a clear environmental story.',
        'platform_sustainability' => 'Platform Sustainability',
        'platform_sustainability_sub' => 'Comprehensive overview of the environmental impact across Notun Alo.',
        'impact_dashboard' => 'Environmental Impact Dashboard',
        'impact_dashboard_missing_db' => 'Import ai-service/emission_factors.sql or start the Flask API to initialize impact analytics.',
        'sustainability_sub' => 'Mobile phone recycling has ~29x higher environmental impact than mixed plastic recycling.',
        'total_co2_saved' => 'Total CO2 Saved',
        'total_water_saved' => 'Total Water Saved',
        'total_energy_saved' => 'Total Energy Saved',
        'category' => 'Category',
        'total_kg' => 'Total kg',
        'co2_saved' => 'CO2 saved',
        'badge' => 'Badge',
        'high_impact_recycling' => 'High Impact Recycling',
        'impact_track_sub' => 'Track your climate, water, and energy savings through recycling.',
        'monthly_impact' => 'Monthly Environmental Impact',
        'monthly_impact_sub' => 'CO2 saved by category over the last 12 months',
        'no_data_yet' => 'No data yet',
        'monthly_impact_chart_title' => 'Your Monthly Environmental Impact (CO₂ kg Saved)'
    ],
    'bn' => [
        'edit_profile_sub' => 'আপনার ব্যক্তিগত তথ্য আপডেট করুন',
        'full_name' => 'পূর্ণ নাম',
        'phone_number' => 'ফোন নম্বর',
        'address' => 'ঠিকানা',
        'upload_profile_picture' => 'প্রোফাইল ছবি আপলোড করুন',
        'site_title' => 'নতুন আলো',
        'dashboard' => 'ড্যাশবোর্ড',
        'shop' => 'শপ',
        'ai_assistant' => 'AI সহকারী',
        'edit_profile' => 'প্রোফাইল সম্পাদনা',
        'logout' => 'লগআউট',
        'hello' => 'হ্যালো',
        'recycling_overview' => 'আপনার রিসাইক্লিং ওভারভিউ',
        'visit_shop' => 'শপ ভিজিট করুন',
        'leaderboard_progress' => 'লিডারবোর্ড অগ্রগতি',
        'current_rank' => 'বর্তমান র‍্যাঙ্ক:',
        'next_rank' => 'পরবর্তী র‍্যাঙ্ক:',
        'max_rank_reached' => 'সর্বোচ্চ র‍্যাঙ্ক অর্জিত!',
        'pts' => 'পয়েন্ট',
        'reward_points' => 'রিওয়ার্ড পয়েন্ট',
        'points_hint' => 'ব্যয় করার জন্য উপলব্ধ পয়েন্ট',
        'completed_pickups' => 'সম্পন্ন পিকআপ',
        'sessions_hint' => 'মোট রিসাইক্লিং সেশন',
        'total_recycled' => 'মোট রিসাইক্লিং',
        'weight_hint' => 'বর্জ্য থেকে সম্পদ রূপান্তর',
        'request_pickup' => 'পিকআপ শিডিউল করুন',
        'schedule_hint' => 'আপনার পরবর্তী সংগ্রহের সময়সূচী নির্ধারণ করুন',
        'waste_category' => 'বর্জ্যের ধরন',
        'select_type' => '— ধরন নির্বাচন করুন —',
        'paper_option' => '📄 কাগজ (৫ পয়েন্ট/কেজি)',
        'plastic_option' => '🧴 প্লাস্টিক (৮ পয়েন্ট/কেজি)',
        'metal_option' => '🔩 ধাতু (১২ পয়েন্ট/কেজি)',
        'paper' => 'কাগজ',
        'plastic' => 'প্লাস্টিক',
        'metal' => 'ধাতু',
        'estimated_weight' => 'আনুমানিক ওজন (কেজি)',
        'preferred_date' => 'পছন্দের পিকআপ তারিখ',
        'submit_request' => 'অনুরোধ জমা দিন',
        'recent_activity' => 'আমার সাম্প্রতিক কার্যকলাপ',
        'activity_hint' => 'আপনার পিকআপ ইতিহাস এবং অবস্থা',
        'no_pickups' => 'এখনো কোনো পিকআপ নেই। আপনার প্রথম পিকআপ অনুরোধ করুন!',
        'scheduled' => 'নির্ধারিত:',
        'top_recyclers' => 'শীর্ষ রিসাইক্লার লিডারবোর্ড',
        'top_recyclers_hint' => 'নতুন আলোর সেরা ব্যবহারকারীগণ',
        'search_products' => 'নাম দিয়ে পণ্য অনুসন্ধান করুন...',
        'recycling' => 'রিসাইক্লিং / পুনর্ব্যবহার',
        'trash_to_treasure' => 'বর্জ্য থেকে সম্পদ',
        'schedule_pickup' => 'পিকআপ শিডিউল করুন',
        'agency_portal' => 'এজেন্সি পোর্টাল',
        'assigned_tasks' => 'বরাদ্দকৃত কাজ',
        'pending_tasks' => 'অপেক্ষমান কাজ',
        'tasks_requiring_collection' => 'সংগ্রহের জন্য অপেক্ষমান কাজ',
        'all_caught_up' => 'সব কাজ সম্পন্ন! আপনার জন্য নতুন কোনো কাজ নেই।',
        'recently_completed' => 'সাম্প্রতিক সম্পন্ন কাজ',
        'last_10_completed' => 'সর্বশেষ ১০টি সম্পন্ন পিকআপ',
        'actual_weight_collected' => 'সংগৃহীত প্রকৃত ওজন (কেজি)',
        'mark_as_collected' => 'সংগৃহীত হিসেবে চিহ্নিত করুন',
        'admin_dashboard' => 'অ্যাডমিন ড্যাশবোর্ড',
        'platform_stats' => 'প্ল্যাটফর্মের পরিসংখ্যান ওভারভিউ',
        'total_waste_collected' => 'মোট বর্জ্য সংগৃহীত',
        'total_pickups' => 'মোট পিকআপ',
        'registered_users' => 'নিবন্ধিত ব্যবহারকারী',
        'products_in_shop' => 'শপে পণ্য',
        'user' => 'ব্যবহারকারী',
        'category' => 'বিভাগ',
        'weight' => 'ওজন',
        'date' => 'তারিখ',
        'action' => 'পদক্ষেপ',
        'my_tasks' => 'আমার কাজ',
        'pickups' => 'পিকআপ',
        'orders' => 'অর্ডার',
        'add_product' => 'পণ্য যোগ করুন',
        'inventory' => 'ইনভেন্টরি',
        'manage_orders' => 'অর্ডার পরিচালনা',
        'manage_orders_sub' => 'পণ্য ক্রয় দেখুন এবং ডেলিভারি এজেন্সি বরাদ্দ করুন',
        'product' => 'পণ্য',
        'payment' => 'পেমেন্ট',
        'status' => 'অবস্থা',
        'assign_agency' => 'এজেন্সি বরাদ্দ করুন',
        'assign' => 'বরাদ্দ করুন',
        'select' => '— নির্বাচন করুন —',
        'no_orders_found' => 'কোনো অর্ডার পাওয়া যায়নি।',
        'manage_pickups' => 'পিকআপ পরিচালনা',
        'manage_pickups_sub' => 'ব্যবহারকারীর পিকআপ অনুরোধ দেখুন এবং এজেন্সিকে বরাদ্দ করুন',
        'inventory_management' => 'ইনভেন্টরি পরিচালনা',
        'inventory_sub' => 'আপসাইকেল শপে বর্তমানে থাকা সমস্ত পণ্য',
        'add_new_product' => 'নতুন পণ্য যোগ করুন',
        'add_product_sub' => 'শপের জন্য একটি নতুন পরিবেশবান্ধব পণ্য তৈরি করুন',
        'confirmed' => 'নিশ্চিতকৃত',
        'pending' => 'অপেক্ষমান',
        'completed' => 'সম্পন্ন',
        'assigned' => 'বরাদ্দকৃত',
        'points' => 'পয়েন্ট',
        'cash' => 'ক্যাশ',
        'points_price' => 'পয়েন্ট মূল্য',
        'cash_price' => 'ক্যাশ মূল্য',
        'stock' => 'স্টক',
        'actions' => 'পদক্ষেপসমূহ',
        'left' => 'অবশিষ্ট',
        'out_of_stock' => 'স্টক আউট',
        'edit' => 'সম্পাদনা',
        'delete' => 'মুছে ফেলুন',
        'delete_confirm' => 'আপনি কি নিশ্চিত যে আপনি এই পণ্যটি মুছে ফেলতে চান?',
        'product_name' => 'পণ্যের নাম',
        'image_url' => 'ছবির URL',
        'description' => 'বিবরণ',
        'price_bdt' => 'মূল্য (BDT)',
        'add_product_btn' => 'শপে পণ্য যোগ করুন',
        'edit_product' => 'পণ্য সম্পাদনা',
        'edit_product_sub' => 'নিচে পণ্যের বিবরণ আপডেট করুন',
        'update_product' => 'পণ্য আপডেট করুন',
        'back_to_inventory' => 'ইনভেন্টরিতে ফিরে যান',
        'save_changes' => 'পরিবর্তন সংরক্ষণ করুন',
        'no_users_yet' => 'এখনও কোনো রিসাইক্লার নেই।',
        'environmental_impact' => 'পরিবেশগত প্রভাব',
        'sustainability_report' => 'টেকসই প্রতিবেদন',
        'impact_intelligence' => 'পরিবেশগত প্রভাব বুদ্ধিমত্তা',
        'impact_desc' => 'আপনার রিসাইক্লিং জলবায়ু, পানি এবং শক্তি সঞ্চয়ে রূপান্তরিত হয়েছে।',
        'co2_prevented' => 'CO2 রোধ',
        'car_trips_avoided' => 'গাড়ির ট্রিপ এড়ানো হয়েছে',
        'water_saved' => 'পানি সাশ্রয়',
        'bottles_saved' => 'বোতল সাশ্রয়',
        'energy_saved' => 'শক্তি সাশ্রয়',
        'phone_charges' => 'ফোন চার্জ',
        'live_impact_loaded' => 'লাইভ ইমপ্যাক্ট লোড হয়েছে',
        'forecast_90_days' => '৯০-দিনের পূর্বাভাস',
        'loading_forecast' => 'পূর্বাভাস লোড হচ্ছে...',
        'story_default' => 'প্রতিটি সম্পন্ন পিকআপ এখানে একটি পরিবেশগত গল্প হিসেবে প্রদর্শিত হবে।',
        'platform_sustainability' => 'প্লাটফর্মের টেকসইতা',
        'platform_sustainability_sub' => 'নতুন আলোর পরিবেশগত প্রভাবের একটি ব্যাপক ওভারভিউ।',
        'impact_dashboard' => 'পরিবেশগত প্রভাব ড্যাশবোর্ড',
        'impact_dashboard_missing_db' => 'পরিবেশগত প্রভাবের বিশ্লেষণ শুরু করতে ai-service/emission_factors.sql ইমপোর্ট করুন বা ফ্লাস্ক এপিআই চালু করুন।',
        'sustainability_sub' => 'মিশ্র প্লাস্টিকের তুলনায় মোবাইল ফোন রিসাইক্লিংয়ের পরিবেশগত প্রভাব প্রায় ২৯ গুণ বেশি।',
        'total_co2_saved' => 'মোট CO2 সাশ্রয়',
        'total_water_saved' => 'মোট পানি সাশ্রয়',
        'total_energy_saved' => 'মোট শক্তি সাশ্রয়',
        'category' => 'ক্যাটাগরি',
        'total_kg' => 'মোট কেজি',
        'co2_saved' => 'CO2 সাশ্রয়',
        'badge' => 'ব্যাজ',
        'high_impact_recycling' => 'উচ্চ প্রভাব রিসাইক্লিং',
        'impact_track_sub' => 'রিসাইক্লিংয়ের মাধ্যমে আপনার জলবায়ু, পানি এবং শক্তি সাশ্রয় ট্র্যাক করুন।',
        'monthly_impact' => 'মাসিক পরিবেশগত প্রভাব',
        'monthly_impact_sub' => 'গত ১২ মাসে ক্যাটাগরি অনুযায়ী CO2 সাশ্রয়',
        'no_data_yet' => 'এখনও কোনো ডেটা নেই',
        'monthly_impact_chart_title' => 'আপনার মাসিক পরিবেশগত প্রভাব (সাশ্রয়কৃত CO₂ কেজি)'
    ]
];

$lang = $translations[$currentLang];
?>